[build-system]
requires = ["setuptools>=42", "wheel"]

[tool.pyright]
reportImportCycles = false
reportUnnecessaryIsInstance = false
typeCheckingMode = "strict"
include = ["dialects", "passes", "traits", "utils"]
ignore = ["utils/z3_to_dialect.py", "utils/integer_to_z3.py", "passes/calculate_smt.py", "tests"]
