[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
reportImportCycles = false
reportUnnecessaryIsInstance = false
typeCheckingMode = "strict"
include = ["xdsl_smt"]
ignore = ["xdsl_smt/utils/z3_to_dialect.py", "xdsl_smt/utils/integer_to_z3.py", "xdsl_smt/passes/calculate_smt.py", "verifier.py", "tests"]
