from xdsl.dialects import arith
from xdsl.ir import Operation

from xdsl_smt.dialects.transfer import (
    NegOp,
    CmpOp,
    AndOp,
    OrOp,
    XorOp,
    AddOp,
    SubOp,
    CountLOneOp,
    CountLZeroOp,
    CountROneOp,
    CountRZeroOp,
    # GetBitWidthOp,
    # UMulOverflowOp,
    SMinOp,
    SMaxOp,
    UMinOp,
    UMaxOp,
    ShlOp,
    LShrOp,
    SelectOp,
    UnaryOp,
    Constant,
    GetAllOnesOp,
    MulOp,
    SetLowBitsOp,
    SetHighBitsOp,
    TransIntegerType,
    GetBitWidthOp,
)

i1_prior_uniform: dict[type[Operation], int] = {
    arith.AndIOp: 1,
    arith.OrIOp: 1,
    arith.XOrIOp: 1,
    CmpOp: 1,
}

int_prior_uniform: dict[type[Operation], int] = {
    NegOp: 1,
    AndOp: 1,
    OrOp: 1,
    XorOp: 1,
    AddOp: 1,
    SubOp: 1,
    SelectOp: 1,
    LShrOp: 1,
    ShlOp: 1,
    UMinOp: 1,
    UMaxOp: 1,
    MulOp: 1,
    CountLOneOp: 1,
    CountLZeroOp: 1,
    CountROneOp: 1,
    CountRZeroOp: 1,
    # SetHighBitsOp,
    # SetLowBitsOp,
}

int_prior_uniform_stronger: dict[type[Operation], int] = {
    NegOp: 10,
    AndOp: 10,
    OrOp: 10,
    XorOp: 10,
    AddOp: 10,
    SubOp: 10,
    SelectOp: 10,
    LShrOp: 10,
    ShlOp: 10,
    UMinOp: 10,
    UMaxOp: 10,
    MulOp: 10,
    CountLOneOp: 10,
    CountLZeroOp: 10,
    CountROneOp: 10,
    CountRZeroOp: 10,
    # SetHighBitsOp,
    # SetLowBitsOp,
}

int_prior_bias: dict[type[Operation], int] = {
    NegOp: 5,
    AndOp: 10,
    OrOp: 10,
    XorOp: 10,
    AddOp: 10,
    SubOp: 10,
    SelectOp: 5,
    LShrOp: 5,
    ShlOp: 5,
    UMinOp: 5,
    UMaxOp: 5,
    MulOp: 2,
    CountLOneOp: 2,
    CountLZeroOp: 2,
    CountROneOp: 2,
    CountRZeroOp: 2,
    # SetHighBitsOp,
    # SetLowBitsOp,
}
